# Generated by Django 6.0 on 2025-12-21 07:27

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(default=store.models.generate_product_code, editable=False, max_length=10, unique=True, verbose_name='Mã sản phẩm')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('category', models.CharField(help_text='Ví dụ: Điện tử, Gia dụng, Thời trang...', max_length=100, verbose_name='Loại sản phẩm')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Hãng sản xuất')),
                ('product_series', models.CharField(blank=True, max_length=100, verbose_name='Dòng sản phẩm')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Năm ra mắt')),
                ('dimensions', models.CharField(blank=True, help_text='Ví dụ: 20x30x50 cm', max_length=100, verbose_name='Kích thước (Dài x Rộng x Cao)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh minh họa')),
                ('price', models.IntegerField(verbose_name='Giá gốc (VNĐ)')),
                ('discount_percent', models.IntegerField(default=0, help_text='Nhập 0 nếu không giảm', verbose_name='Phần trăm giảm (%)')),
                ('discount_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày bắt đầu giảm')),
                ('discount_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc giảm')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
