# Generated by Django 6.0 on 2025-12-21 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_average_rating_product_review_count_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên người gửi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email nhận phản hồi')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='SĐT (Tùy chọn)')),
                ('subject', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung liên hệ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact_files/', verbose_name='Tệp đính kèm')),
                ('status', models.CharField(choices=[('NEW', 'Mới - Chưa đọc'), ('READ', 'Đã xem'), ('REPLIED', 'Đã gửi Email trả lời')], default='NEW', max_length=20, verbose_name='Trạng thái')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú nội bộ (Admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản (nếu có)')),
            ],
            options={
                'verbose_name': 'Liên hệ / Góp ý',
                'verbose_name_plural': 'Danh sách Liên hệ',
                'ordering': ['-created_at'],
            },
        ),
    ]
