# Generated by Django 6.0 on 2025-12-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='attachment',
        ),
    ]
