# Generated by Django 6.0 on 2025-12-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_contact_attachment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
