# Generated by Django 6.0 on 2025-12-21 07:27

import django.db.models.deletion
import login.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(default=login.models.generate_user_code, editable=False, max_length=10, unique=True, verbose_name='Mã User')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='Tên hiển thị (Nickname)')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Tên thật (Để nhận hàng)')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ nhà mặc định')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', '----')], default='Khác', max_length=10, verbose_name='Giới tính')),
                ('profile_picture', models.ImageField(default='default_avatar.png', upload_to='profile_pics', verbose_name='Ảnh đại diện')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
