# Generated by Django 6.0 on 2025-12-21 07:54

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(default=orders.models.generate_order_code, editable=False, max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('full_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('total_amount', models.IntegerField(verbose_name='Tổng tiền đơn hàng')),
                ('payment_method', models.CharField(default='COD', max_length=50, verbose_name='Phương thức thanh toán')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán chưa')),
                ('status', models.CharField(choices=[('Pending', 'Chờ xác nhận'), ('Confirmed', 'Đã xác nhận'), ('Shipping', 'Đang giao hàng'), ('Delivered', 'Giao thành công'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao thành công')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú đơn hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Tên SP lúc mua')),
                ('price', models.IntegerField(verbose_name='Giá lúc mua')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
